### PR TITLE
[Feature #161094027] Create a landing page which is also a login page

### PR DESCRIPTION
**Pull request by Hesbon5600**
**What does this PR do?**
This PR creates the login page for this application

**Description of Task to be completed**
The main tasks to be completed are:
Creation of a login form
Creation of a welcome section on the page

**How should this be manually tested?**
To test this page, clone my repository using the link git@github.com:Hesbon5600/Store-manager.git
Then open the terminal and change the current directory to Store-manager
Finally, launch index.html

Any background context you want to provide?
No

What are the relevant pivotal tracker stories?
#161094027

Screenshots (if appropriate)
screenshot 201

### CODE REVIEW

**Comment by jomasim** [comment]
Good work i could recommend you use basic and easy-to-read font e.g sans serif

**Comment by sharkdevs** [comment]
Good work.
**Recommendations**
Change the Font types. Use Roboto, Open Sans or Museo for that purpose.

**Comment by codeMarble254** [comment]
Great work

**Comment by Krafty-Coder** [comment]
Good UI design, simple and complete...

**Comment by Hesbon5600** [comment]
Thanks

**Pull request closed without merging**
