### PR TITLE
Ft user login ui 161094027

### PR DESCRIPTION
**Pull request by Hesbon5600**
**What does this PR do?**
This PR creates the login page for this application

**Description of Task to be completed**
The main tasks to be completed are:
Creation of a login form
Creation of a welcome section on the page

**How should this be manually tested?**
To test this page, clone my repository using the link git@github.com:Hesbon5600/Store-manager.git
Then open the terminal and change the current directory to Store-manager
Finally, launch index.html

**Any background context you want to provide?**
No

**What are the relevant pivotal tracker stories?**
#161094027

**Screenshots (if appropriate)**
screenshot 202

### CODE REVIEW

**Comment by johnwayodi** [comment]
Looks Amazing. Design is on point

**Comment by Hesbon5600** [comment]
Thanks!

**Comment by jonathanmusila** [comment]
Good job but rename according to the naming conventions #ID Login

**Comment by Hesbon5600** [comment]
Does the branch name really has the #ID or is it just ID

**Comment by Hesbon5600** [comment]
> Good job but rename according to the naming conventions #ID Login

Does the branch name really has the #ID or is it just ID

**Comment by Etomovich** [comment]
Awesome look @Hesbon5600!! Keep up the good work.

**Pull request merged**
